-- ==============================================================================
-- MULTI-TENANT SAAS - CRM, CALCULATION & BILLING TABLES
-- ==============================================================================

-- 1. TENANT DOMAINS (For dynamic multi-domain mapping)
create table public.tenant_domains (
    id uuid primary key default uuid_generate_v4(),
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    domain text not null unique,
    is_verified boolean default false,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- 2. CRM ACTIVITIES (Log employee notes, followups, and status updates on leads)
create table public.crm_activities (
    id uuid primary key default uuid_generate_v4(),
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    lead_id uuid not null references public.leads(id) on delete cascade,
    staff_user_id uuid references auth.users(id) on delete set null,
    activity_type text not null check (activity_type in ('note', 'call', 'email', 'status_change', 'meeting')),
    notes text not null,
    created_at timestamptz default now()
);

-- 3. SAVED CALCULATIONS (Calculator configurations generated by visitors)
create table public.saved_calculations (
    id uuid primary key default uuid_generate_v4(),
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    lead_id uuid references public.leads(id) on delete set null,
    monthly_bill numeric,
    roof_area numeric,
    recommended_kw numeric,
    estimated_cost numeric,
    estimated_savings numeric,
    inputs_json jsonb default '{}'::jsonb,
    created_at timestamptz default now()
);

-- 4. SUBSCRIPTIONS (Billing & payment tier tracking per tenant)
create table public.subscriptions (
    id uuid primary key default uuid_generate_v4(),
    tenant_id uuid not null references public.tenants(id) on delete cascade unique,
    stripe_customer_id text,
    stripe_subscription_id text,
    plan_tier text not null default 'trial' check (plan_tier in ('trial', 'basic', 'pro', 'enterprise')),
    status text not null check (status in ('active', 'past_due', 'canceled', 'incomplete', 'trialing')),
    current_period_end timestamptz,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================

alter table public.tenant_domains enable row level security;
alter table public.crm_activities enable row level security;
alter table public.saved_calculations enable row level security;
alter table public.subscriptions enable row level security;

-- 1. Tenant Domains Policies
create policy "Tenant admins can manage their domains" on public.tenant_domains
    for all using (tenant_id in (select public.get_auth_user_tenant_ids()));

create policy "Public can view domains for resolution" on public.tenant_domains
    for select using (true);

-- 2. CRM Activities Policies (Only employees of the tenant can view/manage activity logs)
create policy "Employees can manage CRM activities" on public.crm_activities
    for all using (tenant_id in (select public.get_auth_user_tenant_ids()));

-- 3. Saved Calculations Policies
create policy "Employees can view calculations" on public.saved_calculations
    for select using (tenant_id in (select public.get_auth_user_tenant_ids()));

create policy "Public can submit calculations" on public.saved_calculations
    for insert with check (true);

-- 4. Subscriptions Policies (Billing info is strictly admin and super_admin read only)
create policy "Tenant admins can view subscription details" on public.subscriptions
    for select using (tenant_id in (select public.get_auth_user_tenant_ids()));

-- ==============================================================================
-- INDEXES & TIMESTAMPS
-- ==============================================================================
create index idx_tenant_domains_tenant_id on public.tenant_domains(tenant_id);
create index idx_tenant_domains_domain on public.tenant_domains(domain);
create index idx_crm_activities_lead_id on public.crm_activities(lead_id);
create index idx_saved_calculations_lead_id on public.saved_calculations(lead_id);
create index idx_subscriptions_tenant_id on public.subscriptions(tenant_id);

create trigger trigger_tenant_domains_updated_at before update on public.tenant_domains for each row execute procedure public.handle_updated_at();
create trigger trigger_subscriptions_updated_at before update on public.subscriptions for each row execute procedure public.handle_updated_at();
