// ─────────────────────────────────────────────────────────────────────────────
// DATABASE / SUPABASE TYPES (Placeholder — will be generated by Supabase CLI)
// ─────────────────────────────────────────────────────────────────────────────

// This file will be auto-generated by: npx supabase gen types typescript
// DO NOT edit this file manually once Supabase is connected

export interface Database {
  public: {
    Tables: {
      // ── Leads Table ──────────────────────────────────────────────────────
      leads: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string | null;
          tenant_id: string | null;
          name: string;
          email: string;
          phone: string | null;
          company: string | null;
          message: string;
          service: string | null;
          city: string | null;
          rooftop_area: number | null;
          electricity_bill: number | null;
          status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'closed' | 'lost';
          source: 'website' | 'whatsapp' | 'referral' | 'social' | 'direct';
          assigned_to: string | null;
          notes: string | null;
          preferred_language: string | null;
        };
        Insert: Omit<Database['public']['Tables']['leads']['Row'], 'id' | 'created_at'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['leads']['Row']>;
        Relationships: [];
      };

      // ── Blog Posts Table ──────────────────────────────────────────────────
      blog_posts: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          title: string;
          slug: string;
          excerpt: string | null;
          content: string;
          cover_image: string | null;
          author_id: string;
          published: boolean;
          published_at: string | null;
          tags: string[];
          locale: string;
          meta_title: string | null;
          meta_description: string | null;
          view_count: number;
        };
        Insert: Omit<
          Database['public']['Tables']['blog_posts']['Row'],
          'id' | 'created_at' | 'updated_at' | 'view_count'
        >;
        Update: Partial<Database['public']['Tables']['blog_posts']['Insert']>;
        Relationships: [];
      };

      // ── Users / Admins Table ──────────────────────────────────────────────
      admin_users: {
        Row: {
          id: string;
          created_at: string;
          email: string;
          name: string;
          role: 'super_admin' | 'admin' | 'sales' | 'support';
          is_active: boolean;
          avatar_url: string | null;
        };
        Insert: Omit<Database['public']['Tables']['admin_users']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['admin_users']['Insert']>;
        Relationships: [];
      };

      // ── Quotes Table ──────────────────────────────────────────────────────
      quotes: {
        Row: {
          id: string;
          created_at: string;
          lead_id: string;
          system_capacity: number;
          total_cost: number;
          subsidy_amount: number;
          net_cost: number;
          payback_period: number;
          status: 'draft' | 'sent' | 'accepted' | 'rejected';
          valid_until: string | null;
          notes: string | null;
        };
        Insert: Omit<Database['public']['Tables']['quotes']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['quotes']['Insert']>;
        Relationships: [];
      };

      // ── FAQs Table ────────────────────────────────────────────────────────
      faqs: {
        Row: {
          id: string;
          created_at: string;
          tenant_id: string;
          category: string;
          question: string;
          answer: string;
          sort_order: number;
          is_active: boolean;
        };
        Insert: Omit<Database['public']['Tables']['faqs']['Row'], 'id' | 'created_at'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['faqs']['Insert']>;
        Relationships: [];
      };

      // ── Testimonials Table ────────────────────────────────────────────────
      testimonials: {
        Row: {
          id: string;
          created_at: string;
          tenant_id: string;
          client_name: string;
          client_role: string | null;
          content: string;
          rating: 1 | 2 | 3 | 4 | 5;
          system_size: string | null;
          savings_estimate: string | null;
          avatar_url: string | null;
          featured: boolean;
          sort_order: number;
        };
        Insert: Omit<Database['public']['Tables']['testimonials']['Row'], 'id' | 'created_at'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['testimonials']['Insert']>;
        Relationships: [];
      };

      // ── Projects Table ────────────────────────────────────────────────────
      projects: {
        Row: {
          id: string;
          created_at: string;
          tenant_id: string;
          title: string;
          category: 'residential' | 'commercial' | 'industrial';
          location: string;
          capacity: string;
          savings: string;
          image_url: string | null;
          case_study_slug: string | null;
          featured: boolean;
          sort_order: number;
        };
        Insert: Omit<Database['public']['Tables']['projects']['Row'], 'id' | 'created_at'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['projects']['Insert']>;
        Relationships: [];
      };

      // ── CRM Activities Table ──────────────────────────────────────────────
      crm_activities: {
        Row: {
          id: string;
          created_at: string;
          tenant_id: string;
          lead_id: string;
          activity_type: string;
          notes: string | null;
        };
        Insert: Omit<Database['public']['Tables']['crm_activities']['Row'], 'id' | 'created_at'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['crm_activities']['Insert']>;
        Relationships: [];
      };

      // ── Tenant Users Table ────────────────────────────────────────────────
      tenant_users: {
        Row: {
          id: string;
          created_at: string;
          user_id: string;
          tenant_id: string;
          role: string;
        };
        Insert: Omit<Database['public']['Tables']['tenant_users']['Row'], 'id' | 'created_at'> & {
          id?: string;
        };
        Update: Partial<Database['public']['Tables']['tenant_users']['Insert']>;
        Relationships: [];
      };
    };

    Views: {
      [_ in never]: never;
    };

    Functions: {
      [_ in never]: never;
    };

    Enums: {
      lead_status: 'new' | 'contacted' | 'qualified' | 'proposal' | 'closed' | 'lost';
      lead_source: 'website' | 'whatsapp' | 'referral' | 'social' | 'direct';
      user_role: 'super_admin' | 'admin' | 'sales' | 'support';
    };
  };
}

// Convenience type helpers
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
